version: '3'
services:
  influxdb:
    image: influxdb 
    container_name: influxdb
    restart: unless-stopped
    network_mode: 'bridge'
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=speedtest
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=spdtst
    volumes:
      - influxdb:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest 
    container_name: grafana
    restart: unless-stopped
    network_mode: 'bridge'
    expose:
      - 3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=grafana_pwd
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
    volumes:
      - grafana:/var/lib/grafana
    links:
      - influxdb
    depends_on:
      - influxdb
  
  speedtest:
    image: rpi-speedtest-cli
    container_name: speedtest
    restart: unless-stopped
    network_mode: 'bridge'
    environment:
      - TEST_INTERVAL=300
      - WRITE_CSV=False
      - WRITE_INFLUXDB=True
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=speedtest
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=spdtst
    volumes:
      - speedtest:/var/lib/speedtest
    links:
      - influxdb
    depends_on:
      - influxdb
      
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    network_mode: 'bridge'
    volumes:
      - /home/pi/Documents/rpi-speedtest-cli/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 81:81
      - 443:443
    links:
      - grafana
      - netdata
      - pihole
    depends_on:
      - grafana
      - netdata
      - pihole
      
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: 'bridge'
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    expose:
      - 80
      - 443
    environment:
      TZ: 'Europe/Vienna'
      WEBPASSWORD: pihole_pwd
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
         
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: raspi.home # set to fqdn of host
    network_mode: 'bridge'
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
volumes:
  influxdb:
  grafana:
  speedtest:
